// Code generated by MockGen. DO NOT EDIT.
// Source: user_get.go

// Package handlers is a generated GoMock package.
package handlers

import (
	domain "BE-JoanaVidon/user-api/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGetHandler is a mock of GetHandler interface.
type MockGetHandler struct {
	ctrl     *gomock.Controller
	recorder *MockGetHandlerMockRecorder
}

// MockGetHandlerMockRecorder is the mock recorder for MockGetHandler.
type MockGetHandlerMockRecorder struct {
	mock *MockGetHandler
}

// NewMockGetHandler creates a new mock instance.
func NewMockGetHandler(ctrl *gomock.Controller) *MockGetHandler {
	mock := &MockGetHandler{ctrl: ctrl}
	mock.recorder = &MockGetHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetHandler) EXPECT() *MockGetHandlerMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGetHandler) Execute(arg0 string, arg1 domain.User) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockGetHandlerMockRecorder) Execute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGetHandler)(nil).Execute), arg0, arg1)
}
